name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with:
          node-version: 20
      - name: Clean install
        working-directory: ./app
        run: npm ci
      - name: Build Nuxt app
        run: npm build
        working-directory: ./app
      - name: Build Express server
        run: npm build
        working-directory: ./server
  
